name: ChickenSandwich2

author: Enhanced Rock

description: Slimefun4 add-on that expands upon Minecrafts food/agriculture

main: me.enhancedrock.chickensandwich2.ChickenSandwich2

website: https://github.com/enhancedrock/ChickenSandwich2

version: ${project.version}

api-version: 1.14

depend:
- Slimefun
